@url =http://localhost:4004

### Base
{{url}}

### GET flashcards
GET {{url}}/flashcards

### GET SINGLE flashcard
GET {{url}}/flashcards/2768

### GET BAD SINGLE flashcard
GET {{url}}/flashcards/qewe




### GET welcomeMessage
GET {{url}}/welcomeMessage

### POST welcomeMessage
POST {{url}}/welcomeMessage
content-type: application/json

{
    "message": "Welcome to welcomee sites. (Changed)!"
}
 
### DELETE flashcard
DELETE {{url}}/flashcards/1658

### DELETE BAD flashcard
DELETE {{url}}/flashcards/asdasd

### BAD LOGIN
POST {{url}}/login
content-type: application/json

{
    "password": "se123"
}

### SUCCESSFUL LOGIN
POST {{url}}/login
content-type: application/json

{
    "password": "123"
}

